elasticsearch:
  image: elasticsearch:2.4.0
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch

yardstick:
  restart: always
  image: opnfv/yardstick:latest
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "8888:5000"

bottlenecks:
  restart: always
  build: bottlenecks/
